name: Update data and Update model

on:
  schedule:
    - cron: '0 4 * * *' # This cron expression runs the job daily
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update
        run: python ./main/main_update.py

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: movies_data.csv
          path: movies_data.csv

  update_modal:
    runs-on: ubuntu-latest
    needs: crawl
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: movies_data.csv
          path: merge_data/

      - name: Update model
        run: python update_model.py
      
      - name: Commit and push the .pkl file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add model_efa/*.pkl
          git add merge_data/final_merged.csv
          git commit -m 'Update .pkl files in merge_data directory'
          git push
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
